# Server Configuration
server.port=8080

# Spring MVC Configuration
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

# AWS S3 Configuration
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}

# AWS RDS Configuration
spring.datasource.url=${AWS_RDS_URL}
spring.datasource.username=${AWS_RDS_USERNAME}
spring.datasource.password=${AWS_RDS_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# i18n Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
